# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_assignment_question_mltiple4_assignment_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='semester',
            field=models.CharField(default=b'2017Spring', max_length=200),
        ),
    ]
