# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_week_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_full_title', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
