# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_assignment_question_python_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_question',
            name='is_answer',
            field=models.BooleanField(default=0),
        ),
    ]
