# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_assignment_question_repeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_python_code', models.TextField()),
                ('answer_element_type', models.CharField(max_length=100)),
                ('answer_element_style', models.CharField(max_length=300)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Assignment_question')),
            ],
        ),
    ]
