# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_student_assignment_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='assignment_short_title',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
