# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 19:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0041_assignments_assignment_date_tbd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_play_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=100)),
                ('time_seconds', models.FloatField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
