# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_week_week_level_of_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='week_level_of_difficulty',
        ),
    ]
