# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20171012_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saved_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_content', models.TextField()),
                ('my_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.My_User')),
            ],
        ),
    ]
