# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_saved_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_questions',
            name='time_stamp',
            field=models.DateTimeField(default=None),
        ),
    ]
