# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_saved_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_questions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
