# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20170317_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_question_mltiple4',
            name='assignment_question_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Assignment_question'),
            preserve_default=False,
        ),
    ]
