# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20170703_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_question',
            name='python_code',
            field=models.TextField(default=b''),
        ),
    ]
