# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_assignments_assignment_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='assignment_date_tbd',
            field=models.BooleanField(default=0),
        ),
    ]
