# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_saved_questions_time_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved_questions',
            name='my_user',
        ),
        migrations.DeleteModel(
            name='Saved_Questions',
        ),
    ]
