# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_final_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='assignment_due_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignments',
            name='assignment_order',
            field=models.IntegerField(default=1),
        ),
    ]
