# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_assignment_question_is_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment_question',
            old_name='question_type',
            new_name='element_type',
        ),
    ]
