# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20170704_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_question',
            name='element_style',
            field=models.CharField(default=b'', max_length=300),
        ),
    ]
