# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_assignment_question_element_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment_question',
            old_name='is_answer',
            new_name='parent_question_id',
        ),
    ]
