# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20170704_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_question',
            name='parent_question_id',
            field=models.IntegerField(default=-1),
        ),
    ]
