# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-23 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_audio_play_history_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_answer',
            name='placeholder',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
