# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-29 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_assignment_answer_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_assignment_answers',
            name='last_submit_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
