# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_remove_week_week_level_of_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=200)),
                ('section_time', models.CharField(max_length=200)),
            ],
        ),
    ]
