# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20171012_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='section_id',
            new_name='section_title',
        ),
    ]
